version: '3.0'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  testenv:
    build: .
    command: sh /app/test.sh
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=password
      - RAILS_ENV=test
      - PORT=3000
