# Build dependencies
FROM ruby:2.6.5
RUN apt-get update -qq && apt-get install -y nodejs yarn postgresql-client

# Install project
RUN mkdir /app
WORKDIR /app
RUN gem install bundler -v 2.1.4
COPY Gemfile /app/Gemfile
RUN bundle install
COPY . /app
RUN yarn
RUN rails db:setup

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
RUN chmod +x /app/test.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

# Start the main process.
CMD ["rails", "test"]
